### ISSUE TITLE
Does not apply to strict standards

### ISSUE THREAD

**Issue by thinkluke** [macdonaldr93/yamm-nav-walker#1]
Strict Standards: Declaration of Yamm_Nav_Walker::start_lvl() should be compatible with Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array) in /Applications/MAMP/htdocs/**/wp-content/themes/**/yamm-nav-walker.php on line 0

**Comment by thinkluke** [comment]
Just replace:

function start_lvl(&$output, $depth, $args = array())

with: ( added $depth = 0 )

function start_lvl(&$output, $depth = 0, $args = array())

**Comment by macdonaldr93** [comment]
Awesome! Thank you. I'll consume this now.

**Comment by macdonaldr93** [comment]
I've updated the repository. I'll mark the issue as closed now.
