### ISSUE TITLE
Is compatible with bootstrap 4?

### ISSUE THREAD

**Issue by kanlukasz** [macdonaldr93/yamm-nav-walker#10]
Is compatible with bootstrap 4? and what about multilevel menu?

**Comment by macdonaldr93** [comment]
@kanlukasz unfortunately it doesn't support Bootstrap 4. I wasn't planning on looking into supporting that until Bootstrap 4 has an official release. Looks like they're still beta.

What do you mean by multilevel? This essentially builds out the megamenu nav so It would have multilevels but they're all displayed in a single dropdown. Like this:

![https://screenshot.click/17-55-wmec7-uuozd.png](https://screenshot.click/17-55-wmec7-uuozd.png)

**Comment by kanlukasz** [comment]
@macdonaldr93 - thanks for your response. i mean something like this:

![screenshot-2017-10-17 components](https://user-images.githubusercontent.com/30685349/31678354-371989c0-b36e-11e7-860d-87a50e9c0fd4.png)

**Comment by macdonaldr93** [comment]
No problem! And yeah, I think you would just want the standard bootstrap walker. I've used https://github.com/Themekraft/_tk/blob/master/includes/bootstrap-wp-navwalker.php in the past.
