### ISSUE TITLE
How can I add a widget at the end of my YAMM menu?

### ISSUE THREAD

**Issue by jsbls** [macdonaldr93/yamm-nav-walker#2]
I'm trying to implement a dynamic_sidebar after all my submenu items, but am not finding the correct spot inside the walker. What's the correct way to do this?

**EDIT:**
I'm able to accomplish it with jQuery using appendTo, just wondering if there is a more straightforward way from inside the walker.

**Comment by macdonaldr93** [comment]
@jsbls you could override the `end_lvl` method and append your widget before the closing tag for the menu. Let me know if that works.

See: https://codex.wordpress.org/Class_Reference/Walker#Abstract_Methods

**Comment by jsbls** [comment]
Ok, let me give it a try right now. Thanks!

**EDIT:**

So the following happens. If I add plain HTML, it renders correctly, but PHP gets placed before the `<ul class="yamm">` wrapper. For example:

```
public function end_lvl( &$output, $depth = 0, $args = array() )
{
    $output .= ($depth == 0) ?
        "\n<div>Hello, world</div>\n" .
        "\n</div>\n" . // .row
        "\n</div>\n" . // yamm-content
        "\n</ul>\n" // .dropdown-menu
        : "\n</ul>\n"; // else .subcat-ul
}
```

renders (I'm ignoring the _else_ statement)

```
<ul class='dropdown-menu'>
    <div class='yamm-content'>
        <div class='row'>
            <div>Hello, world</div>
        </div>
    </div>
</ul>
```

**But**

```
public function end_lvl( &$output, $depth = 0, $args = array() )
{
    $output .= ($depth == 0) ?
        "\n" . dynamic_sidebar('sidebar-featured-shop') . "\n" .
        "\n</div>\n" . // .row
        "\n</div>\n" . // yamm-content
        "\n</ul>\n" // .dropdown-menu
        : "\n</ul>\n"; // else .subcat-ul
}
```

...renders

```
<div class="sidebar-featured">(Sidebar content)</div>
<ul class="nav navbar-nav>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="//localhost:3000/shop/">Shop <b class="caret"></b></a> 
        <ul class="dropdown-menu">
            <div class="yamm-content">
                ...
            </div>
        </ul>
    </li>
</ul>
```

**Comment by macdonaldr93** [comment]
@jsbls sorry I went offline there for a while. Did you end up resolving this?

**Comment by jsbls** [comment]
I can't remember! 😅  Let me go through the project and let you know. I think in the end what I did was add an Ads Plugin and insert the shortcode, but I'm not sure. Will update soon.

**Comment by macdonaldr93** [comment]
haha no problem! Just wanted to check in. Felt bad I left you hanging lol
