### ISSUE TITLE
How do I make it so that it supports images

### ISSUE THREAD

**Issue by ghost** [macdonaldr93/yamm-nav-walker#3]
I want to support images for sub menu dropdowns. How do I achieve it with this walker code?

**Comment by AssessmentDay** [comment]
checkout this tutorial, may help. [link to tutorial](http://www.omnicoda.com/blog/wordpress-development/beginners-guide-wordpress-menus-bootstrap-navigation)

**Comment by macdonaldr93** [comment]
@AssessmentDay thanks for that post! I had no idea this was being referenced in tutorials haha that's awesome

**Comment by macdonaldr93** [comment]
@user247 did that fix your issue? Closing this for now.

**Comment by AssessmentDay** [comment]
@macdonaldr93 No worries, Glad I could help.
