### ISSUE TITLE
Column Counts

### ISSUE THREAD

**Issue by jdcauley** [macdonaldr93/yamm-nav-walker#5]
I'm correct in reading that the number of columns in the menu is pretty locked to a single count?

**Comment by macdonaldr93** [comment]
@jdcauley yes, I had hardcoded `col-sm-4` in this walker. You could pretty easily just find and replace that class if you needed a different count.

**Comment by jdcauley** [comment]
@macdonaldr93, Thanks, I tracked it down, didn't realize before this that there isn't away to identify the number of sub items in a list.
