### ISSUE TITLE
Apply all menus in wordpress

### ISSUE THREAD

**Issue by ranapartap** [macdonaldr93/yamm-nav-walker#7]
Hi

Thanks for great work. I liked the simplicity of menus.

My question is that how can we apply all type of menu styles as listed in example like accordion, classic etc. on wordpress menu,

Any example will be appreciated.

Thank you
Rana

**Comment by macdonaldr93** [comment]
@ranapartap Hey! Just trying to clarify what you're asking. Are you trying to apply different styles from Bootstrap? Or adding your own styles?

**Comment by ranapartap** [comment]
Hi @macdonaldr93

Thank you for your reply. I would like to know as shown in your example in a bootstrap based WP theme how can we apply both menu styles accordion as well as classic menus using wordpress menu system (wp_menu) to produce the result something like below:

Home  -> No submenu 
Services -> 3 submenus (0 depth) -> Menu 1, Menu 2, Menu 3
Products -> 5 submens (1 depth) -> Prod Cat 1, Prod Cat 2, Prod Cat 3 (Each submenu has 2-3 more submenus) as show on in  picture.

Hope it is clear now. 
Thank you in advance.
![screenshot 15](https://user-images.githubusercontent.com/4345093/29806794-c59ae4be-8cae-11e7-9869-b76dfc96971d.png)
![screenshot 16](https://user-images.githubusercontent.com/4345093/29806793-c59ae54a-8cae-11e7-8d0e-4509dc63fcc2.png)

**Comment by macdonaldr93** [comment]
Ahhh I see. I didn't realize Yamm had those other options. Currently this only supports the grid layout
